apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calibre-web.fullname" . }}-envs
data:
  TZ: {{ .Values.calibreWeb.timezone }}
  {{- range $k, $v := .Values.calibreWeb.configuration }}
  _CALIBRE_{{ upper $k }}: "{{ $v}}"
  {{- end }}
