{{- if .Values.persistence.data.enabled }}
{{- if not .Values.persistence.data.existingClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "calibre-web.fullname" . }}-data
  labels:
    {{- include "calibre-web.labels" . | nindent 4 }}
{{- if .Values.persistence.data.annotations }}
annotations:
{{ toYaml .Values.persistence.data.annotations | indent 2 }}
{{- end }}
spec:
  accessModes:
  - {{ .Values.persistence.data.accessMode }}
  storageClassName: {{ default .Values.persistence.data.storageClass "" }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- end }}
{{- end }}
