#apiVersion: v1
#kind: Secret
#metadata:
#  name: {{ template "calibre-web.fullname" . }}-secret
#  labels:
#    app.kubernetes.io/name: {{ include "calibre-web.name" . }}
#    helm.sh/chart: {{ include "calibre-web.chart" . }}
#    app.kubernetes.io/instance: {{ .Release.Name }}
#    app.kubernetes.ui/managed-by: {{ .Release.Service }}
#type: Opaque
#stringData:
#  002-configure.sh: |-
#    #!/bin/bash
#
#    apt update && apt install -y sqlite3
#    sqlite3 /config/app.db \
#      "UPDATE settings SET config_calibre_dir='{{ .Values.calibreWeb.libraryDir }}'"
#    {{- range $k, $v := .Values.calibreWeb.configuration }}
#    {{- if kindIs "string" $v }}
#    sqlite3 /config/app.db "UPDATE settings SET {{ $k }}='{{ $v }}'"
#    {{- else if kindIs "bool" $v }}
#    sqlite3 /config/app.db "UPDATE settings SET {{ $k }}={{ int $v }}"
#    {{- else if kindIs "int" $v }}
#    sqlite3 /config/app.db "UPDATE settings SET {{ $k }}={{ $v }}"
#    {{- end }}
#    {{- end }}
#
#  003-admin.sh: |-
#    #!/bin/bash
#    python3 cps.py -s admin:{{ .Values.calibreWeb.adminPassword }}
