apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wekan.fullname" . }}-envs
  labels:
    {{- include "wekan.labels" . | nindent 4 }}
stringData:
  MONGO_URL: mongodb://{{ index .Values.mongodb.auth.usernames 0 }}:{{ index .Values.mongodb.auth.passwords 0 }}@{{ include "mongodb.service.nameOverride" .Subcharts.mongodb }}:27017/{{ index .Values.mongodb.auth.databases 0 }}
  MAIL_URL: smtp{{ if .Values.wekan.smtp.secure }}s{{ end }}://{{ if or .Values.wekan.smtp.username .Values.wekan.smtp.password }}{{ .Values.wekan.smtp.username }}:{{ .Values.wekan.smtp.password }}{{ end }}@{{ .Values.wekan.smtp.host }}:{{ .Values.wekan.smtp.port }}
  MAIL_FROM: {{ .Values.wekan.smtp.from }}
  {{- if .Values.wekan.openid.enabled }}
  OAUTH2_ENABLED: "true"
  OAUTH2_CLIENT_ID: {{ .Values.wekan.openid.clientId }}
  OAUTH2_SERVER_URL: {{ .Values.wekan.openid.serverUrl }}
  OAUTH2_AUTH_ENDPOINT: {{ .Values.wekan.openid.authEndpoint }}
  OAUTH2_USERINFO_ENDPOINT: {{ .Values.wekan.openid.userinfoEndpoint }}
  OAUTH2_TOKEN_ENDPOINT: {{ .Values.wekan.openid.tokenEndpoint }}
  OAUTH2_SECRET: {{ .Values.wekan.openid.secret }}
  OAUTH2_ID_MAP: {{ .Values.wekan.openid.idMap }}
  OAUTH2_USERNAME_MAP: {{ .Values.wekan.openid.usernameMap }}
  OAUTH2_FULLNAME_MAP: {{ .Values.wekan.openid.fullnameMap }}
  OAUTH2_EMAIL_MAP: {{ .Values.wekan.openid.emailMap }}
  {{- end }}
  {{- with .Values.wekan.extraEnvsSecret }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
