apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wekan.fullname" . }}-envs
  labels:
    {{- include "wekan.labels" . | nindent 4 }}
data:
  WRITABLE_PATH: {{ .Values.persistence.mountPath }}
  ROOT_URL: http{{ ternary "s" "" .Values.ingress.tls.enabled }}://{{ .Values.host }}
  {{- with .Values.wekan.extraEnvsConfig }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
