{{- if .Values.persistence.config.enabled }}
{{- if not .Values.persistence.config.existingClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "jellyfin.fullname" . }}-config
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
{{- if .Values.persistence.config.annotations }}
  annotations:
{{ toYaml .Values.persistence.config.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
  - {{ .Values.persistence.config.accessMode }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
{{- end }}
{{- end }}
