{{- if .Values.persistence.cache.enabled }}
{{- if not .Values.persistence.cache.existingClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "jellyfin.fullname" . }}-cache
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
{{- if .Values.persistence.cache.annotations }}
  annotations:
{{ toYaml .Values.persistence.cache.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
  - {{ .Values.persistence.cache.accessMode }}
  storageClassName: {{ .Values.persistence.cache.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size | quote }}
{{- end }}
{{- end }}
