apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrentvpn.fullname" . }}
  labels:
    {{- include "qbittorrentvpn.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      {{- include "qbittorrentvpn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qbittorrentvpn.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrentvpn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - sh
            - -xc
            - |
              apt update && apt install -y curl
              curl -s https://configs.ipvanish.com/configs/configs.zip -o /config/configs.zip
              mkdir -p /config/openvpn
              unzip -p /config/configs.zip $VPN_CONFIG.ovpn > /config/openvpn/01-$VPN_CONFIG.ovpn
              unzip -p /config/configs.zip ca.ipvanish.com.crt > /config/openvpn/ca.ipvanish.com.crt
              sed -i.bak 's/proto udp/proto tcp-client/g' /config/openvpn/01-$VPN_CONFIG.ovpn
          env:
            - name: VPN_PROVIDER
              value: {{ .Values.openvpn.provider }}
            - name: VPN_CONFIG
              value: {{ .Values.openvpn.config }}
          volumeMounts:
          {{- if .Values.persistence.config.enabled }}
            - mountPath: /config
              name: config
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -xc
            - |
              sed -i.bak -E 's/([ ]*)exec openvpn (.*) \&/\1exec openvpn --proto tcp-client \2 \&/g' /etc/openvpn/start.sh
              /etc/openvpn/start.sh
          env:
            - name: VPN_TYPE
              value: openvpn
            - name: VPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.openvpn.existingSecret (printf "%s-openvpn" (include "qbittorrentvpn.fullname" .)) }}
                  key: username
            - name: VPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.openvpn.existingSecret (printf "%s-openvpn" (include "qbittorrentvpn.fullname" .)) }}
                  key: password
            - name: LAN_NETWORK
              value: {{ .Values.openvpn.lanNetwork }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.persistence.data.enabled }}
            - mountPath: /downloads
              name: data
          {{- end }}
          {{- if .Values.persistence.config.enabled }}
            - mountPath: /config
              name: config
          {{- end }}
            - name: dev-tun
              mountPath: /dev/net/tun
      volumes:
      {{- if .Values.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ default .Values.persistence.data.existingClaim (printf "%s-data" (include "qbittorrentvpn.fullname" . )) }}
      {{- end }}
      {{- if .Values.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ default .Values.persistence.config.existingClaim (printf "%s-config" (include "qbittorrentvpn.fullname" . )) }}
      {{- end }}
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
