apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrentvpn.fullname" . }}
  labels:
    {{- include "qbittorrentvpn.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      {{- include "qbittorrentvpn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qbittorrentvpn.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrentvpn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VPN_ENABLED
              value: {{ (.Values.vpn.enabled | ternary "yes" "no")|quote }}
            {{- if .Values.vpn.enabled }}
            - name: VPN_TYPE
              value: {{ .Values.vpn.type }}
            {{- if eq .Values.vpn.type "openvpn" }}
            - name: VPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.vpn.openvpn.existingSecret (printf "%s-openvpn" (include "qbittorrentvpn.fullname" .)) }}
                  key: username
            - name: VPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.vpn.openvpn.existingSecret (printf "%s-openvpn" (include "qbittorrentvpn.fullname" .)) }}
                  key: password
            {{- end }}
            - name: LAN_NETWORK
              value: {{ .Values.vpn.lanNetwork }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.http.port }}
              protocol: TCP
            - name: torrent
              containerPort: {{ .Values.incoming.port }}
              protocol: TCP
            - name: udp
              containerPort: {{ .Values.incoming.port }}
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.persistence.data.enabled }}
            - mountPath: /downloads
              name: data
          {{- end }}
          {{- if .Values.persistence.config.enabled }}
            - mountPath: /config/qBittorrent
              name: config
          {{- end }}
          {{- if .Values.vpn.existingConfigMap }}
            - mountPath: /config
              name: vpn-config
          {{- end }}
          {{- if .Values.vpn.existingSecret }}
            - mountPath: /config/{{ .Values.vpn.type }}
              name: vpn-config
          {{- end }}
            - name: dev-tun
              mountPath: /dev/net/tun
      volumes:
      {{- if .Values.persistence.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.data.existingClaim }}{{ .Values.persistence.data.existingClaim }}{{ else }}{{ printf "%s-data" (include "qbittorrentvpn.fullname" . ) }}{{ end }}
      {{- end }}
      {{- if .Values.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.config.existingClaim }}{{ .Values.persistence.config.existingClaim }}{{ else }}{{ printf "%s-config" (include "qbittorrentvpn.fullname" . ) }}{{ end }}
      {{- end }}
      {{- if .Values.vpn.existingConfigMap }}
        - name: vpn-config
          configMap:
            name: {{ .Values.vpn.existingConfigMap }}
      {{- end }}
      {{- if .Values.vpn.existingSecret }}
        - name: vpn-config
          secret:
            secretName: {{ .Values.vpn.existingSecret }}
      {{- end }}
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
