{{- if .Values.persistence.data.enabled }}
{{- if not .Values.persistence.data.existingClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "qbittorrentvpn.fullname" . }}-data
  labels:
    {{- include "qbittorrentvpn.labels" . | nindent 4 }}
{{- if .Values.persistence.data.annotations }}
annotations:
{{ toYaml .Values.persistence.data.annotations | indent 2 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- end }}
{{- end }}
{{- if .Values.persistence.config.enabled }}
{{- if not .Values.persistence.config.existingClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "qbittorrentvpn.fullname" . }}-config
  labels:
    {{- include "qbittorrentvpn.labels" . | nindent 4 }}
{{- if .Values.persistence.config.annotations }}
annotations:
{{ toYaml .Values.persistence.config.annotations | indent 2 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
{{- end }}
{{- end }}
