{{- if not .Values.openvpn.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qbittorrentvpn.fullname" . }}-openvpn
  labels:
    {{- include "qbittorrentvpn.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.openvpn.username | b64enc }}
  password: {{ .Values.openvpn.password | b64enc }}
{{- end }}
