{{- if .Values.http.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrentvpn.fullname" . }}-http
  labels:
    {{- include "qbittorrentvpn.labels" . | nindent 4 }}
{{- if .Values.http.service.annotations }}
annotations:
{{ toYaml .Values.http.service.annotations | indent 2 }}
{{- end }}
spec:
  type: {{ .Values.http.service.type }}
  ports:
    - port: {{ .Values.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qbittorrentvpn.selectorLabels" . | nindent 4 }}
{{- end }}
