apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
    {{- include "openldap.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  admin-username: {{ .Values.openldap.admin.username | b64enc | quote }}
  admin-password: {{ .Values.openldap.admin.password | b64enc | quote }}
  {{- if .Values.openldap.configAdmin.enabled }}
  config-username: {{ .Values.openldap.configAdmin.username | b64enc | quote }}
  config-password: {{ .Values.openldap.configAdmin.password | b64enc | quote }}
  {{- end }}
