apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sharry.fullname" . }}-conf
  labels:
    {{- include "sharry.labels" . | nindent 4 }}
stringData:
  sharry.conf: |
    {{ include "sharry.conf" . | nindent 4 }}
