apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linkding.fullname" . }}
  labels:
    {{- include "linkding.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "linkding.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "linkding.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "linkding.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.linkding.username }}
            - name: LD_SUPERUSER_NAME
              value: {{ .Values.linkding.username }}
          {{- end }}
          {{- if .Values.linkding.password }}
            - name: LD_SUPERUSER_PASSWORD
              value: {{ .Values.linkding.password }}
          {{- end }}
          {{- if .Values.linkding.disableBackgroundTasks }}
            - name: LD_DISABLE_BACKGROUND_TASKS
              value: {{ .Values.linkding.disableBackgroundTasks | int | quote }}
          {{- end }}
          {{- if .Values.linkding.disableUrlValidation }}
            - name: LD_DISABLE_URL_VALIDATION
              value: {{ .Values.linkding.disableUrlValidation | int | quote }}
          {{- end }}
          {{- if .Values.linkding.requestTimeout }}
            - name: LD_REQUEST_TIMEOUT
              value: {{ .Values.linkding.requestTimeout | quote }}
          {{- end }}
          {{- if .Values.linkding.serverPort }}
            - name: LD_SERVER_PORT
              value: {{ .Values.linkding.serverPort | quote }}
          {{- end }}
          {{- if .Values.linkding.contextPath }}
            - name: LD_CONTEXT_PATH
              value: {{ .Values.linkding.contextPath }}
          {{- end }}
          {{- if .Values.linkding.enableAuthProxy }}
            - name: LD_ENABLE_AUTH_PROXY
              value: {{ .Values.linkding.enableAuthProxy | int | quote }}
          {{- end }}
          {{- if .Values.linkding.proxyUsernameHeader }}
            - name: LD_PROXY_USERNAME_HEADER
              value: {{ .Values.linkding.proxyUsernameHeader }}
          {{- end }}
          {{- if .Values.linkding.proxyLogoutUrl }}
            - name: LD_PROXY_LOGOUT_URL
              value: {{ .Values.linkding.proxyLogoutUrl }}
          {{- end }}
          {{- if .Values.linkding.csrfTrustedOrigins }}
            - name: LD_CSRF_TRUSTED_ORIGINS
              value: {{ .Values.linkding.csrfTrustedOrigins }}
          {{- end }}
          {{- if .Values.postgresql.enabled }}
            - name: LD_DB_ENGINE
              value: postgres
            - name: LD_DB_HOST
              value: {{ template "postgresql.primary.fullname" .Subcharts.postgresql }}
            - name: LD_DB_PORT
              value: {{ .Values.postgresql.primary.service.ports.postgresql | quote }}
            - name: LD_DB_DATABASE
              value: {{ .Values.postgresql.global.postgresql.auth.database }}
            - name: LD_DB_USER
              value: {{ .Values.postgresql.global.postgresql.auth.username }}
            - name: LD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.global.postgresql.auth.existingSecret | default (printf "%s-postgresql" .Release.Name ) }}
                  key: password
          {{- else }}
            - name: LD_DB_ENGINE
              value: sqlite
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.linkding.serverPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: {{ include "linkding.fullname" . }}
              mountPath: /etc/linkding/data
{{- end }}
{{- if .Values.persistence.enabled }}
      volumes:
        - name: {{ include "linkding.fullname" . }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ include "linkding.fullname" . }}{{- end }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
