apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-envs
  labels:
    {{- include "outline.labels" . | nindent 4 }}
data:
  SECRET_KEY: {{ .Values.outline.secretKey|b64enc }}
  UTILS_SECRET: {{ .Values.outline.utilsSecret|b64enc }}
  DATABASE_URL: {{ (printf "postgres://%s:%s@%s:5432/%s" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.global.postgresql.auth.password (include "postgresql.v1.primary.fullname" .Subcharts.postgresql) .Values.postgresql.global.postgresql.auth.database)|b64enc }}
