apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "outline.fullname" . }}-envs
  labels:
    {{- include "outline.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.outline.nodeEnv }}
  DATABASE_CONNECTION_POOL_MIN: {{ .Values.outline.databaseConnectionPoolMin | quote }}
  DATABASE_CONNECTION_POOL_MAX: {{ .Values.outline.databaseConnectionPoolMax | quote }}
  PGSSLMODE: {{ .Values.outline.pgsslMode }}
  URL: https://{{ .Values.host }}
  COLLABORATION_URL:
  FILE_STORAGE: {{ .Values.persistence.type }}
  FILE_STORAGE_UPLOAD_MAX_SIZE: {{ .Values.outline.uploadMaxSize | toJson | trimAll "\"" | quote }}
  FILE_STORAGE_IMPORT_MAX_SIZE: {{ (default .Values.outline.importMaxSize .Values.outline.uploadMaxSize) | toJson | trimAll "\"" | quote }}
  FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE: {{ (default .Values.outline.workspaceImportMaxSize .Values.outline.uploadMaxSize) | toJson | trimAll "\"" | quote }}
  FORCE_HTTPS: {{ .Values.outline.forceHttps | quote }}
  ENABLE_UPDATES: {{ .Values.outline.enableUpdates | quote }}
  DEBUG: {{ .Values.outline.debug }}
  LOG_LEVEL: {{ .Values.outline.logLevel }}
  WEB_CONCURRENCY: {{ .Values.outline.webConcurrency | quote }}
