{{- if .Values.outline.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-oidc
  labels:
    {{- include "outline.labels" . | nindent 4 }}
data:
  OIDC_CLIENT_ID: {{ .Values.outline.oidc.clientId|b64enc }}
  OIDC_CLIENT_SECRET: {{ .Values.outline.oidc.clientSecret|b64enc }}
  OIDC_AUTH_URI: {{ .Values.outline.oidc.authUri|b64enc }}
  OIDC_TOKEN_URI: {{ .Values.outline.oidc.tokenUri|b64enc }}
  OIDC_USERINFO_URI: {{ .Values.outline.oidc.userinfoUri|b64enc }}
  OIDC_LOGOUT_URI: {{ .Values.outline.oidc.logoutUri|b64enc }}
  OIDC_DISPLAY_NAME: {{ .Values.outline.oidc.displayName|b64enc }}
  OIDC_USERNAME_CLAIM: {{ .Values.outline.oidc.usernameClaim|b64enc }}
  OIDC_SCOPES: {{ .Values.outline.oidc.scopes|b64enc }}
{{- end }}
