apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-s3
  labels:
    {{- include "outline.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.persistence.s3.accessKey|b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.persistence.s3.secretKey|b64enc }}
  AWS_REGION: {{ .Values.persistence.s3.region|b64enc }}
  AWS_S3_UPLOAD_BUCKET_URL: {{ .Values.persistence.s3.url|b64enc }}
  AWS_S3_UPLOAD_BUCKET_NAME: {{ .Values.persistence.s3.bucket|b64enc }}
  AWS_S3_FORCE_PATH_STYLE: {{ .Values.persistence.s3.forcePathStyle|toString|b64enc }}
  AWS_S3_ACL: {{ .Values.persistence.s3.acl|b64enc }}
