{{- if .Values.outline.smtp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-smtp
  labels:
    {{- include "outline.labels" . | nindent 4 }}
data:
  SMTP_HOST: {{ .Values.outline.smtp.host|b64enc }}
  SMTP_PORT: {{ .Values.outline.smtp.port|toString|b64enc }}
  SMTP_USERNAME: {{ .Values.outline.smtp.username|b64enc }}
  SMTP_PASSWORD: {{ .Values.outline.smtp.password|b64enc }}
  SMTP_FROM_EMAIL: {{ .Values.outline.smtp.fromEmail|b64enc }}
  SMTP_REPLY_EMAIL: {{ .Values.outline.smtp.replyEmail|b64enc }}
  SMTP_SECURE: {{ .Values.outline.smtp.secure|toString|b64enc }}
{{- end }}
