apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tikiwiki.fullname" . }}
  labels:
    {{- include "tikiwiki.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tikiwiki.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tikiwiki.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tikiwiki.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sh", "-c" ]
          args:
            - |
              php console.php database:install -n
              php console.php database:update -n
          env:
            - name: TIKI_DB_HOST
              value: {{ include "mariadb.primary.fullname" .Subcharts.mariadb }}
            - name: TIKI_DB_USER
              value: {{ .Values.mariadb.auth.username }}
            - name: TIKI_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.fullname" .Subcharts.mariadb }}
                  key: mariadb-password
            - name: TIKI_DB_NAME
              value: {{ .Values.mariadb.auth.database }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TIKI_DB_HOST
              value: {{ include "mariadb.primary.fullname" .Subcharts.mariadb }}
            - name: TIKI_DB_USER
              value: {{ .Values.mariadb.auth.username }}
            - name: TIKI_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.fullname" .Subcharts.mariadb }}
                  key: mariadb-password
            - name: TIKI_DB_NAME
              value: {{ .Values.mariadb.auth.database }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
