apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tikiwiki.fullname" . }}
  labels:
    {{- include "tikiwiki.labels" . | nindent 4 }}
    {{- include "tikiwiki.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.tikiwiki.adminPassword | b64enc | quote }}
